Revert "Add chronological sorting to test results and key=value to --info."
This reverts commit ff94ab47bd69ce811ffdeb90e0d10a5802c7c0a6, which broke
the ability of generate_test_results.py to gather data on crashes.

Example failure:
  http://chromegw/i/chromeos/builders/link%20paladin/builds/9128

Traceback (most recent call last):
  File "/usr/bin/generate_test_report", line 631, in <module>
    main()
  File "/usr/bin/generate_test_report", line 627, in main
    generator.Run()
  File "/usr/bin/generate_test_report", line 568, in Run
    self._GenerateReportText()
  File "/usr/bin/generate_test_report", line 532, in _GenerateReportText
    crashes[crash].add(test)
NameError: global name 'test' is not defined

Original commit message:

Long suites have lengthy result lists and its hard to see how an
early failure can affect subsequent tests.  Add an option for sorting
test results in chronological order. Grabs a human-readable localtime
for grepping and a timestamp for sorting.

Also adds keys to --info csv data so that automated tools may find specific
info keys like bios version and ec version.

BUG=chromium-os:34919
TEST=generate_test_report --strip "/tmp/..." --sort-chron "/tmp/..."
TEST=multiple variations with/without --sort-cron, --csv --info and --no-debug.

Change-Id: Ia09bef1a5853bd70f49988352747268ed8d4c5d2
Reverted-Change-Id: I9839e55526c5871a0e28434e8434224a2223e8c7
Reviewed-on: https://gerrit.chromium.org/gerrit/34375
Reviewed-on: https://gerrit.chromium.org/gerrit/34844
Reviewed-by: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>